// const mockTasks = [
//   {
//     taskId: 1,
//     parentTaskId: null,
//     title: "Task 1",
//     description: "Mô tả Task 1",
//     status: 1,
//     priority: "Trung bình",
//     type: "code",
//     taskColumnId: 1,
//     assigneeId: 1,
//     createdBy: 1,
//     startDate: "2024-02-11",
//     endDate: "2024-02-20",
//     completedAt: null,
//   },
//   {
//     taskId: 2,
//     parentTaskId: null,
//     title: "Task 2",
//     description: "Mô tả Task 2",
//     status: 2,
//     priority: "Khó",
//     type: "học bài",
//     taskColumnId: 2,
//     assigneeId: 2,
//     createdBy: 2,
//     startDate: "2024-02-12",
//     endDate: "2024-02-22",
//     completedAt: null,
//   },
//   {
//     taskId: 3,
//     parentTaskId: null,
//     title: "Task 3",
//     description: "Mô tả Task 3",
//     status: 3,
//     priority: "Rất khó",
//     type: "nghiên cứu",
//     taskColumnId: 3,
//     assigneeId: 3,
//     createdBy: 3,
//     startDate: "2024-02-13",
//     endDate: "2024-02-23",
//     completedAt: null,
//   },
// ];

// export default mockTasks;
